#@data/values
---
application:
  name: micro-pet
service:  
  replicas: 1
  backend:
    observability: true
    mode: RANDOM_NUMBER
    frequencyError: 10
  gui:
    color: green
    config_path: /workspace/dist/assets
    broker_service: http://pets.hermes.avilab.top/pets
environment:
  name: aks/east2
  ingress: istio
  domain:
    internal: .micropets-supplychain.svc.cluster.local
    exposed: azu.hermes.avilab.top

