#@ load("@ytt:data", "data")

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-config-creation-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-creation-role
subjects:
  - kind: ServiceAccount
    name: #@ data.values.service_account_name

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-creation-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - create
      - update
      - delete
      - patch
      - watch
      - get

