#@ load("@ytt:data", "data")

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-git-writing-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: git-writing-role
subjects:
  - kind: ServiceAccount
    name: #@ data.values.service_account_name

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: git-writing-role
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - taskruns
    verbs:
      - list
      - create
      - update
      - delete
      - patch
      - watch
