#@ load("@ytt:data", "data")

#
# The service-account is referenced by the workload and provides permissions for
# Cartographer to create templated objects
#
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: #@ data.values.service_account_name
