#@ load("@ytt:data", "data")
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workload-role
subjects:
  - kind: ServiceAccount
    name: #@ data.values.service_account_name
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workload-role
rules:
  - apiGroups:
      - source.toolkit.fluxcd.io
      - kpack.io
      - kapp.k14s.io/v1alpha1
      - kappctrl.k14s.io
      - serving.knative.dev/v1
      - carto.run
      - source.apps.tanzu.vmware.com
    resources:
      - gitrepositories
      - images
      - configs
      - apps
      - services
      - runnables
      - workloads
      - imagerepositories
    verbs:
      - list
      - create
      - update
      - delete
      - patch
      - watch
      - get
