#@data/values
---
application:
  name: mypet
service:  
  name: gui
  port: 8080
  image: harbor.mytanzu.xyz/library/micropet-tap-dogs@sha256:b24abdf40753f64cdcfd40b4c9cdbfc45254e53e83243d9e5329b9daf2521be8
  replicas: 1    
  config_path: /workspace/dist/assets
  config_filename: config.json
  backend:
    observability: false
    mode: RANDOM_NUMBER
    frequencyError: 10  
  gui:    
    color: green    
    broker_service: http://pets.svc.cnr.mytanzu.xyz/pets     
environment:
  name: aws/eu-west-3
  ingress: istio
  domain:
    internal: micropets-supplychain.svc.cluster.local
    exposed: front.mytanzu.xyz
  
