apiVersion: carto.run/v1alpha1
kind: ClusterConfigTemplate
metadata:
  name: micropet-service-intermediate-config-gui
spec: 
  params:
    - name: broker_service
      default: #@ "http://not_set/pets/v1/default" 
    - name: color
      default: "green"  
  configPath: .data
  ytt: |
    #@ load("@ytt:data", "data")
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: #@ data.values.workload.metadata.name
    data:
      #@yaml/text-templated-strings
      values: |
        #@data/values
        ---       
        application:
          name: micro-pet
        service:  
          name: $(workload.metadata.name)$
          port: 8080
          image: (@= data.values.image @)    
          config_path: /workspace/dist/assets
          config_filename: config.json          
          gui:            
            broker_service: $(params.broker_service)$
            color: $(params.color)$                               
      schema: |
        #@data/values-schema
        ---
        application:
          name: name
        service:
          name: name
          port: 0
          image: image
          replicas: 1
          config_path: config_path
          config_filename: config_filename                       
          gui:
            color: color
            broker_service: broker_service
        environment:
          name: name
          ingress: ingress
          domain:
            internal: internal
            exposed: exposed
