apiVersion: carto.run/v1alpha1
kind: ClusterConfigTemplate
metadata:
  name: micropet-service-intermediate-config
spec:
  params:
    - name: port
      default: 7003
    - name: mode
      default: "RANDOM_NUMBER"
    - name: observability
      default: false 
    - name: usedb
      default: false
  configPath: .data
  ytt: |
    #@ load("@ytt:data", "data")
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: #@ data.values.workload.metadata.name
    data:
      #@yaml/text-templated-strings
      values: |
        #@data/values
        ---     
        application:
          name: micro-pet   
        service:  
          name: $(workload.metadata.name)$
          port: $(params.port)$
          image: (@= data.values.image @)    
          config_path: /config
          config_filename: pets_config.json
          usedb: $(params.usedb)$          
      schema: |
        #@data/values-schema
        ---
        application:
          name: name
        service:
          name: name
          port: 0
          image: image
          replicas: 1
          config_path: config_path
          config_filename: config_filename 
          usedb: false  
          gui:
            color: color
            broker_service: broker_service
          backend:
            frequencyError: 0
            observability: true
            mode: "RANDOM_NUMBER"                            
        environment:
          name: name
          ingress: ingress
          domain:
            internal: internal
            exposed: exposed
