apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: micropet-service-supply-chain-git-gui
spec:
  selector:
    app.tanzu.vmware.com/workload-type: micropet-service-git-gui
  #
  #
  #   source-provider <--[src]-- image-builder <--[img]--- config-provider  <--[configmap]---  git-writer
  #     GitRepository               Image                    ConfigMap                         Git Commit
  #
  resources:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: micropet-source
    
    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: micropet-gui-image
      sources:
        - resource: source-provider
          name: source
    
    - name: config-provider
      templateRef:
        kind: ClusterConfigTemplate
        name: micropet-service-intermediate-config-gui
      sources:
        - resource: source-provider
          name: source
      images:
        - resource: image-builder
          name: image      
      params:        
        - name: brokerService
          value: $(workload.spec.params[?(@.name=="broker_service")].value)$        
        - name: color
          value: $(workload.spec.params[?(@.name=="color")].value)$
        - name: usedb
          value: false
        - name: component
          value: gui
    - name: git-writer
      templateRef:
        kind: ClusterTemplate
        name: git-writer
      configs:
        - resource: config-provider
          name: data
      sources:
        - resource: source-provider
          name: source
      
