#@data/values
---
application:
  name: micro-pet
service:  
  replicas: 1
  backend:
    observability: true
    mode: RANDOM_NUMBER
    frequencyError: 10
environment:
  name: aks/east1
  domain:
    internal: .micropets-supplychain.svc.cluster.local
    exposed: east1.mytanzu.xyz

