#@data/values
---
application:
  name: micro-pet
service:  
  replicas: 1
  backend:
    observability: true
    mode: RANDOM_NUMBER
    frequencyError: 10
  gui:
    color: green
    config_path: /workspace/dist/assets
    broker_service: /pets
environment:
  name: aks/east1
  ingress: istio
  domain:
    internal: .micropets-supplychain.svc.cluster.local
    exposed: east1.mytanzu.xyz

