---
#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: aso-controller-settings
  namespace: azureserviceoperator-system
stringData:
  AZURE_SUBSCRIPTION_ID: #@ data.values.SUBSCRIPTION_ID
  AZURE_TENANT_ID: #@ data.values.TENANT_ID
  AZURE_CLIENT_ID: #@ data.values.CLIENT_ID
  AZURE_CLIENT_SECRET: #@ data.values.CLIENT_SECRET
