#@data/values
---
service:
  name: cats
  port: 7002
  mode: RANDOM_NUMBER
  replicas: 1
  version: latest
  virtual_host: europe2.mytanzu.xyz
  image: harbor.mytanzu.xyz/library/micropet-tap-cats:1.0.0
  observability: false
  broker_service: http://europe2.mytanzu.xyz/pets
  dns_suffix: .micropets-europe2.svc.cluster.local
application:
  name: micro-pet
registry:
  server: harbor.mytanzu.xyz/library

