---
apiVersion: v1
kind: ConfigMap
metadata:
  name: desired-namespaces
  namespace: tap-namespace-provisioning
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
    namespace-provisioner.apps.tanzu.vmware.com/no-overwrite: "" 
data:
  namespaces.yaml: |
    #@data/values
    ---
    namespaces:
    - name: micropets-birds
      language: java
      database: postgres
    - name: micropets-cats
      language: golang      
    - name: micropets-gui
      language: angular  
    
