---
apiVersion: v1
kind: ConfigMap
metadata:
  name: desired-namespaces
  namespace: tap-namespace-provisioning
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
    namespace-provisioner.apps.tanzu.vmware.com/no-overwrite: ""
data:
  namespaces.yaml: |
    #@data/values
    ---
    namespaces:
    - name: micropets-int
      languages: 
      - java
      - golang
      databases: 
      - postgres
    - name: micropets-dev
      languages: 
      - java
      - golang
      databases: 
      - postgres
    
