#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ def in_list(property, value):
#@  return hasattr(data.values, property) and ( value in data.values[property])
#@ end
#@ if in_list('languages', 'golang'):
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: golang-test-pipeline
  labels:
    apps.tanzu.vmware.com/pipeline: test-golang
spec:
  params:
    - name: source-url
    - name: source-revision
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
        steps:
          - name: test
            image: golang
            script: |-
              cd `mktemp -d`
              wget -qO- $(params.source-url) | tar xvz -m
              echo "GoLang Test...."  
              echo "go test...."             
              #go test              
              echo "GoLang Test....Skipped "
#@ end