#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ def in_list(key, list):
#@  return hasattr(data.values, key) and (data.values[key] in list)
#@ end
#@ if in_list('language', ['golang']):
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: golang-test-pipeline
  labels:
    apps.tanzu.vmware.com/pipeline: test-golang
spec:
  params:
    - name: source-url
    - name: source-revision
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
        steps:
          - name: test
            image: golang
            script: |-
              cd `mktemp -d`
              wget -qO- $(params.source-url) | tar xvz -m
              echo "GoLang Test"
              go test
#@ end