#@data/values
---
service_account_name: cartographer-deliverable-sa
git_writer:
  server: github.com
  repository: bmoussaud/mygitwriter.git
  branch: main
environment: azure/aks-east1
application: micropets