---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yestask
spec:
  steps:
    - name: untar
      image: ubuntu
      script: |
        #!/bin/bash        
        echo "Running tests............................................"  
        sleep 4
        echo "Running tests..........................................OK"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: fake-test-pipeline
  labels:
    apps.tanzu.vmware.com/pipeline: test
spec:
  description: >-
    The Fake Test pipeline builds source from a Git repository into a container image and run tests using maven
  tasks:
    - name: fetch-and-test
      taskRef:
        name: yestask
  params:
    - name: source-url
      description: A git repo url where the source code resides.
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: fake-test-pipeline-2
spec:
  pipelineRef:
    name: fake-test-pipeline
  params:
    - name: source-url
      value: http://source-controller-manager-artifact-service.source-system.svc.cluster.local./imagerepository/dev-tap/birds/a7f45518df9075a1d70db45b0f0609e003861a60caeb4261c2726cf05de2d2d8.tar.gz
