---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: untar
spec:
  workspaces:
    - description: The workspace consisting of untar project.
      name: source
  steps:
    - name: untar
      image: ubuntu
      script: |
        #!/bin/bash        
        cd /workspace/source
        tar zxvf /workspace/source/sources.tar.gz       
        chmod -R 777 /workspace 
        find /workspace -ls
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mymaventask
spec:
  workspaces:
    - description: Maven
      name: source
  steps:
    - name: test
      image: gcr.io/cloud-builders/mvn
      script: |
        #!/bin/bash
        set -x 
        id 
        id
        find /workspace -ls 
        cd /workspace/source        
        mvn -X test -Dproject.build.sourceEncoding=UTF-8 -Dproject.reporting.outputEncoding=UTF-8

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-test-pipeline
  labels:
    apps.tanzu.vmware.com/pipeline: not_used_test
spec:
  description: >-
    The Mvn pipeline builds source from a Git repository into a container image and run tests using maven
  workspaces:
    - name: source-ws
      description: Location where source is stored.
  params:
    - name: source-url
      description: A git repo url where the source code resides.
    - name: SOURCE_REFERENCE
      description: The branch, tag or SHA to checkout.
      default: ""
    - name: SOURCE_SUBPATH
      description: A subpath within checked out source where the source to build is located.
      default: ""
  tasks:
    - name: fetch-from-git
      taskRef:
        name: wget
      params:
        - name: url
          value: $(params.source-url)
        - name: diroptions
          value:
            - "-O"
        - name: filename
          value: sources.tar.gz
      workspaces:
        - name: wget-workspace
          workspace: source-ws
    - name: untar
      runAfter:
        - fetch-from-git
      taskRef:
        name: untar
      workspaces:
        - name: source
          workspace: source-ws
    - name: run-tests
      runAfter:
        - untar
      taskRef:
        name: maven
      workspaces:
        - name: source
          workspace: source-ws
        - name: maven-settings
          workspace: source-ws
      params:
        - name: MAVEN_IMAGE
          value: docker.io/library/maven:3.8-jdk-11
        - name: GOALS
          value:                   
            - test
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: maven-test-pipeline-13
spec:
  pipelineRef:
    name: maven-test-pipeline
  params:
    - name: source-url
      value: http://source-controller-manager-artifact-service.source-system.svc.cluster.local./imagerepository/dev-tap/birds/d4dbe7297c0ff33661574a20b6df884d86ef0fb14d54a112b88dc383e629d189.tar.gz
  workspaces:
    - name: source-ws # this workspace name must be declared in the Pipeline
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 1Gi
