#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-credentials
  annotations:
    kpack.io/docker: #@ data.values.registry.server
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.registry.username
  password: #@ data.values.registry_password
---
apiVersion: v1
kind: Secret
metadata:
  name: pull-harbor-credentials
  annotations:
    kpack.io/docker: #@ data.values.registry.server
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.registry.username
  password: #@ data.values.registry_password
