#@ load("@ytt:data", "data")
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: micropet-service-account
#@ if data.values.registry.username != "":
secrets:
  - name: registry-credentials
imagePullSecrets:
  - name: registry-credentials
#@ end
