#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: micropet-kpack-service-account
secrets:
  - name: kpack-registry-credentials
imagePullSecrets:
  - name: pull-kpack-registry-credentials
