#@ load("@ytt:data", "data")
#@ load("helpers.star","gen_labels")
#@yaml/text-templated-strings
---
#@ if data.values.service.component == "gui":
apiVersion: v1
kind: ConfigMap
metadata:
  labels: #@ gen_labels({ })  
  annotations:
    kapp.k14s.io/versioned : ""
  name: #@ data.values.service.name + "-config"
data:
  (@=  data.values.service.config_filename @): |-
    {  
      "petServiceUrl": "(@=  data.values.service.gui.broker_service @)",
      "stage": "(@=  data.values.environment.name @)",
      "debug": "False",
      "stage_color": "(@=  data.values.service.gui.color @)",
      "load_one_by_one": "True"
    }
#@ end