#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
---
#! Generate a secret including the TO-TOKEN to activate the observabilty in micropets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-aria-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-azure-backend
  target:
    name: aria-credentials
    template:
      type: servicebinding.io/configuration
      data:
        type: app-configuration-aria
        observability.enable: "false"
        observability.token: "{{ .ariaopsforapptoken | toString }}"
  data:
    - secretKey: ariaopsforapptoken
      remoteRef:
        key: TO-TOKEN
---

