#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-aria-credentials-tpl
data:
  config.yaml: |
    type: app-configuration-aria
    observability.enable: "false"
    observability.token: "{{ .ariaopsforapptoken }}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-aria-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-azure-backend
  target:
    name: aria-credentials
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: external-aria-credentials-tpl
            items:
              - key: config.yaml
  data:
    - secretKey: ariaopsforapptoken
      remoteRef:
        key: TO-TOKEN
---

