#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
---
#! tap-registry exported from tapp-install using secretexports.secretgen.carvel.dev
#! but it has defined in the azure keyvault.
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-aria-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-azure-backend
  target:
    template:      
      type: app-configuration-aria
      observability.enable: "false"
      observability.token: "{{ .aria-ops-for-app-token | toString }}"      
    name: aria-credentials-benoit
    creationPolicy: Owner
  data:
  - secretKey: aria-ops-for-app-token
    remoteRef:
      key: TO-TOKEN
---