#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-aria-credentials-tpl
data:
  config.yaml: |
    type: app-configuration-aria
    observability.enable: "false"
    observability.token: "{{ .aria-ops-for-app-token }}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-aria-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-azure-backend
  target:
    name: secret-to-be-created
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            # name of the configmap to pull in
            name: external-aria-credentials-tpl
            # here you define the keys that should be used as template
            items:
              - key: config.yaml
  data:
    - secretKey: aria-ops-for-app-token
      remoteRef:
        key: TO-TOKEN
---

