apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: micropet-gui-service-supply-chain
spec:
  selector:
    app.tanzu.vmware.com/workload-type: micropet-gui-service
  #
  #
  #   source-provider <--[src]-- image-builder  <--[img]--- config <--[config]--- deployer
  #     GitRepository               Image                     App                   App
  #
  #
  components:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: micropet-source
    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: micropet-gui-image
      sources:
        - component: source-provider
          name: source
    - name: configuration
      templateRef:
        kind: ClusterConfigTemplate
        name: micropet-gui-service-config
      sources:
        - component: source-provider
          name: source
      images:
        - component: image-builder
          name: image      
    - name: deploy
      templateRef:
        kind: ClusterTemplate
        name: micropet-gui-deploy      
      configs:
        - component: configuration
          name: petconfig