apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: micropet-service-supply-chain
spec:
  selector:
    app.tanzu.vmware.com/workload-type: micropet-service
  #
  #
  #   source-provider <--[src]-- image-builder  <--[img]--- config <--[config]--- deployer
  #     GitRepository               Image                     App                   App
  #
  #
  components:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: micropet-source
    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: micropet-image
      sources:
        - component: source-provider
          name: source
    - name: configuration
      templateRef:
        kind: ClusterConfigTemplate
        name: micropet-service-config
      sources:
        - component: source-provider
          name: source
      images:
        - component: image-builder
          name: image
      params:        
        - name: mode
          value: $(workload.spec.params[?(@.name=="mode")].value)$
        - name: port
          value: $(workload.spec.params[?(@.name=="port")].value)$
        - name: observability
          value: $(workload.spec.params[?(@.name=="observability")].value)$
    - name: deploy
      templateRef:
        kind: ClusterTemplate
        name: micropet-deploy      
      configs:
        - component: configuration
          name: petconfig
