#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind": "ConfigMap", "metadata":{"name": "config-domain"}})
---
data:
  #@overlay/remove
  _example:
#@overlay/match missing_ok=True
#@yaml/text-templated-strings
  (@=  str(data.values.service.domain) @): |

