#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: dogs
  labels:
    app.tanzu.vmware.com/workload-type: micropets-delivery
spec:
  serviceAccountName: #@ data.values.service_account_name
  source:
    git:
      url: #@ "http://" + data.values.git_writer.server + "/" + data.values.git_writer.repository
      ref:
        branch: #@ data.values.git_writer.branch
  params:
  - name: environment
    value: #@ data.values.environment
  - name: application
    value: #@ data.values.application
---
apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: fishes
  labels:
    app.tanzu.vmware.com/workload-type: micropets-delivery
spec:
  serviceAccountName: #@ data.values.service_account_name
  source:
    git:
      url: #@ "http://" + data.values.git_writer.server + "/" + data.values.git_writer.repository
      ref:
        branch: #@ data.values.git_writer.branch
  params:
  - name: environment
    value: #@ data.values.environment
  - name: application
    value: #@ data.values.application
---
apiVersion: carto.run/v1alpha1  
kind: Deliverable
metadata:
  name: cats
  labels:
    app.tanzu.vmware.com/workload-type: micropets-delivery
spec:
  serviceAccountName: #@ data.values.service_account_name
  source:
    git:
      url: #@ "http://" + data.values.git_writer.server + "/" + data.values.git_writer.repository
      ref:
        branch: #@ data.values.git_writer.branch
  params:
  - name: environment
    value: #@ data.values.environment
  - name: application
    value: #@ data.values.application
---
apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: pets
  labels:
    app.tanzu.vmware.com/workload-type: micropets-delivery
spec:
  serviceAccountName: #@ data.values.service_account_name
  source:
    git:
      url: #@ "http://" + data.values.git_writer.server + "/" + data.values.git_writer.repository
      ref:
        branch: #@ data.values.git_writer.branch
  params:
  - name: environment
    value: #@ data.values.environment
  - name: application
    value: #@ data.values.application
---
apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: gui
  labels:
    app.tanzu.vmware.com/workload-type: micropets-delivery-gui
spec:
  serviceAccountName: #@ data.values.service_account_name
  source:
    git:
      url: #@ "http://" + data.values.git_writer.server + "/" + data.values.git_writer.repository
      ref:
        branch: #@ data.values.git_writer.branch
  params:
  - name: environment
    value: #@ data.values.environment
  - name: application
    value: #@ data.values.application
---
apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: vegeta
  labels:
    app.tanzu.vmware.com/workload-type: simple-delivery
spec:
  serviceAccountName: #@ data.values.service_account_name
  source:
    git:
      url: #@ "http://" + data.values.git_writer.server + "/" + data.values.git_writer.repository
      ref:
        branch: #@ data.values.git_writer.branch
  params:
  - name: environment
    value: #@ data.values.environment
  - name: application
    value: loader/001