#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
---
#@ def config():
tap:  
  version: "1.4.2"
  namespace: tap-install
  devNamespace: dev-tap
  
  supply_chain: testing_scanning
  
  logo: #@ base64.encode(data.read('tap-logo.png'))

  #! Set Backstage catalogs to include by default.
  catalogs:
  - https://github.com/bmoussaud/micropets-app/blob/master/catalog-info.yaml

  registry:    
    host: #@ data.values.registry.server
    repositories:
      buildService: library/tanzu-build-service
      ootbSupplyChain: library/tanzu-supply-chain

  domains:
    main: tap4.eu.aks.mytanzu.xyz
  
  metadatastore:
    ca: empty
    auth_token: empty

#@ end
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tap-install-gitops
  namespace: tap-install-gitops
  annotations:
    kapp.k14s.io/versioned : ""
data:
  tap-config.yml: #@ yaml.encode(config())
