#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
---
#@ def config():
tap:  
  version: "1.4.2"
  namespace: tap-install
  devNamespace: dev-tap
  
  supply_chain: testing_scanning
  
  logo: #@ base64.encode(data.read('tap-logo.png'))

  #! Set Backstage catalogs to include by default.
  catalogs:
  - https://github.com/bmoussaud/micropets-app/blob/master/catalog-info.yaml

  registry:    
    host: #@ data.values.registry.server
    repositories:
      buildService: library/tanzu-build-service
      ootbSupplyChain: library/tanzu-supply-chain

  domains:
    main: tap4.eu.aks.mytanzu.xyz
  
  metadatastore:
    #  export APP_CA=$(kubectl get secret -n metadata-store app-tls-cert -o json | jq -r ".data.\"ca.crt\"")
    # app_ca: empty
    app_ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4RENDQWRpZ0F3SUJBZ0lRTzdlZGVPK1VGVnN0S2hncU9pU1NkREFOQmdrcWhraUc5dzBCQVFzRkFEQVMKTVJBd0RnWURWUVFERXdkallTMWpaWEowTUI0WERUSXpNREV4TVRBNE5EQTBObG9YRFRJME1ERXhNVEE0TkRBMApObG93RWpFUU1BNEdBMVVFQXhNSFkyRXRZMlZ5ZERDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU5OOXNtSXkrSTdqS1lxbVQrUzBWVVJESHh6VThkUDVEQ3EwdmRqNTJOWHZZOFAvQUNZU0ptNXcKUHVtd0l3eS9KaU1yNjNKTldqaVhQYUhZMk9FYXI4LzZpYkp5RExnbzhPUXR2Q00rSXlKb3NudXBRWDJXVklkSgpYN1oweFR4Y3E5Y2hNUmd4bGNCSmNlNjlyT05PNkNNWEN0WW5BcnFoSTVNNUh3Ymo1L2dlZEo1QkZCcnNIZ21KCkpvVHEzV3liTnpmRmpleHJYNmhzM21LM2ordGhkTjBjYU9vZjJJOGJibFNpUGs1Rmx3N2ZGZEwwMm8rUDlsN0wKclpLRlFtZy9BU1V0aGhFY3JJUkRicGN0RG0yNnFEY1h5V3pmNzlMbWV2Ly9zRkVtRWMrQmhuVDVhRXN1azljZAo4ZjZ3L0NnK3oveXBTVStQbmNTeTA1d1lyRVl2dnZrQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trCk1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZBaFMvVWdEdTNvaUJFcVlmWm5vaURpZTZTNDYKTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCemQ1ZDg2QXFaZTRWc0UyRHdrN2cvS0M5WGZGSXlBeXVFNFZ2QQozNnZ6LzVBb1FFaE4zYVFQUjM5dkVJMWJzZzhaNGRsWXMrUU9TU3ZhUWRCb0VjN3hITit3N1lZQnRqaFpsY2lQClZsWFR0RStvekFmNFlCcFdzWVl0T1huV21UNGZ2cURTL3Jmdk03anptQnBTbFNpWUlHa1Y1UXB5YjFRS0JpQkoKeDFYSTJQSUdPTlc4aWxzNFRLS2xmZ1lyaUNMQXBnb1FlRmZLeWs2Ujd0SGlSOTZPRnNtWSsxeVcvMmMzS2VVQwppRndTS2tFcnBMeWd5eEtnYlVzSnpSSzdUR1F4SEFnR2hpNFNJc3ZGL2xGZS91QTA3K0tVbTFkSFl0N2ZjZVRtCjBPTllqZjJnSGdONUs2cHlzd2JOZzdndFd4MUl2Qm1yclJZNC9LT25jYWJVRS8zLwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    # export AUTH_TOKEN=`kubectl get secret metadata-store-read-write-client -n metadata-store -ojsonpath="{.data.token}" | base64 -d`
    # auth_token: empty
    auth_token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlJQSzc0WGFMWjhhQ3RqdjBKbjRmUTZJRGM1N1hSRGlRU2toNHk4aU9vcmsifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtZXRhZGF0YS1zdG9yZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJtZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJtZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImY4MzAyZTY0LWMyYjAtNDJlMS05MjdiLTI1ZDQwZmFjZDYxNyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDptZXRhZGF0YS1zdG9yZTptZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCJ9.MtcYjcGd5m3i7uy9-yLImFQQsKH-hOl1-gw3gb_9NpSNm31OZmT12EFW0B4pjdscGXHA-HYydk_-EaBqzhgGY4TbV1PZKo7mAcA4zce6d8ZJ-DOsLu9oX3dCnwS6iWVOy9sAqSSqS3V7OTJVCKxvzY7FZ7WxwUl4yIJaCdzebGkxgb7zZbuPKtP7uFRrHJcbsyBEje1L2PDv0qaL2wCn5tDd_3BNwOvJVWCMv77EF9GNzY7PSGJaxKylAbdog7RM61_7nT3WVo8VfDJ83VPraYYLDaASUwy9Hgi3rYEteEZgNZ2g8u6MXDz4OtCjoExePB3RfeqaHz4cfQ4N5hmhc6aQPVC-WJfrgRPHS6i1t1KWDCxagvFRBtATGbx_Da0JxxK-KX7OP9GdeK2t1OQ_6suSt-ZGZMlwk8aIkcpT_dFP6gwyeEuHE_vkOAT50mMrjci7_lIA6PeheCbCmCA_nGIyEgts7iM8MmXuhHEb1S5NkXI399YfxFwuMYwEHnMqK0K2k9mPykut6vx7fHFatW29LHuoOySLZpuJ9mhbCDpDK2KUFm1zSNDYsnwzO1snRT2wfRk_GCkTKstaBSWQgcmD6u0pfMZ3Sq5wxVTxgRtJptviX4D3cnxC1DN6fzpvVE5oJBEjHzX010pIlkvdO8ccSkOErpUdBlVOQ2ExlFc

#@ end
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tap-install-gitops
  namespace: tap-install-gitops
  annotations:
    kapp.k14s.io/versioned : ""
data:
  tap-config.yml: #@ yaml.encode(config())
