#@ load("@ytt:data", "data")
#@yaml/text-templated-strings
#@ load("helpers.star","gen_labels")
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name:  #@ data.values.service.name
  labels: #@ gen_labels({ })
  #  networking.knative.dev/visibility: cluster-local
  #  networking.knative.dev/ingress.class: istio   
  annotations:
    service.subdomain: #@ data.values.service.name+".svc"    
    #kapp.k14s.io/versioned-explicit-ref: |
    #  apiVersion: v1
    #  kind: ConfigMap
    #  name: (@=  str(data.values.service.name) @)-config
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      # TODO : manage sa
      #serviceAccountName: tap-default
      volumes:
        - name: config-volume
          configMap:
            name:  #@ data.values.service.name + "-config"
            items:            
            - key: #@ data.values.service.config_filename  
              path: #@ data.values.service.config_filename          
      containers:
        - name:  #@ data.values.service.name
          image: #@ data.values.service.image
          ports:
          - containerPort: #@ data.values.service.port
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - name: config-volume
              mountPath: #@ data.values.service.config_path  
          env:
            - name: SERVICE_CONFIG_DIR
              value: #@ data.values.service.config_path  
          livenessProbe:
            httpGet:
              path: /liveness
              port: #@ data.values.service.port
          readinessProbe:
            httpGet:
              path: /readiness
              port: #@ data.values.service.port
