#@ load("@ytt:data", "data")
#@ if data.values.deliverable:
apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: cats
  labels:
    app.tanzu.vmware.com/workload-type: micropets-delivery
spec:
  source:
    git:
      url: #@ "http://" + data.values.git_writer.server + "/" + data.values.git_writer.repository
      ref:
        branch: #@ data.values.git_writer.branch
  params:
  - name: environment
    value: aws/tkg-uat-1
  - name: application
    value: micropets
#@ end
