apiVersion: carto.run/v1alpha1
kind: ClusterDelivery
metadata:
  name: micropets-delivery
spec:
  selector:
    app.tanzu.vmware.com/workload-type: micropets-delivery

  params:
    - name: application
      default: micropets
    - name: environment
      default: aws/prod-1
  #
  #
  #   source-provider <--[src]--  Service deployer
  #     GitRepository               App
  resources:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: gitops-source

    - name: deployer
      templateRef:
        kind: ClusterDeploymentTemplate
        name: app-deploy
      deployment:
        resource: source-provider
---
apiVersion: carto.run/v1alpha1
kind: ClusterDelivery
metadata:
  name: simple-delivery
spec:
  selector:
    app.tanzu.vmware.com/workload-type: simple-delivery

  params:
    - name: application
      default: micropets
    - name: environment
      default: aws/prod-1
  #
  #
  #   source-provider <--[src]--   K8S deployer
  #     GitRepository               App
  resources:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: gitops-source

    - name: deployer
      templateRef:
        kind: ClusterDeploymentTemplate
        name: deploy-apply
      deployment:
        resource: source-provider