#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: ClusterDeploymentTemplate
metadata:
  name: micropet-app-deploy
spec:
  observedCompletion:
    succeeded:
      key: '.status.conditions[?(@.type=="ReconcileSucceeded")].status'
      value: 'True'
    failed:
      key: '.status.conditions[?(@.type=="ReconcileSucceeded")].status'
      value: 'False'
  template:
    apiVersion: kappctrl.k14s.io/v1alpha1
    kind: App
    metadata:
      name: $(deliverable.metadata.name)$
    spec:
      serviceAccountName: #@ data.values.service_account_name
      fetch:
        - http:
            url: $(sources.rules.url)$               
            subPath: kapp/service  
#   on AKS Connection reset / refused when downloading the content, so switch to git
#        - http:
#            url: $(source.url)$            
        - http:
            url: $(sources.gitops.url)$       
            subPath: applications/$(params.application)$/$(deliverable.metadata.name)$
        - http:
            url: $(sources.gitops.url)$        
            subPath: environments/$(params.environment)$
      template:
        - ytt: 
            ignoreUnknownComments: true                               
      deploy:
        - kapp:
            rawOptions: ["--diff-changes=true"]
