apiVersion: carto.run/v1alpha1
kind: ClusterDelivery
metadata:
  name: micropets-delivery
spec:
  selector:
    app.tanzu.vmware.com/workload-type: micropets-delivery

  params:
    - name: application
      default: micropets
    - name: environment
      default: aws/prod-1  
  #
  #
  #   gitops-provider <--[gitops]---------   Service deployer
  #     GitRepository                           App
  #                                        |
  #   deployment-provider   <--[rules]-----| 
  #     GitRepository               
  #
  resources:    
    - name: gitops-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: gitops-source
    - name: deployment-rules-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: deployment-source        
    - name: deployment-provider  
      templateRef:
        kind: ClusterDeploymentTemplate
        name: micropet-app-deploy      
      deployment:
        resource: gitops-provider
      sources:
        - resource: gitops-provider
          name: gitops
        - resource: deployment-rules-provider
          name: rules
      params:
        - name: deployment_rules
          default: kapp/service 

