#@ load("@ytt:data", "data")

#
# The service-account is referenced by the delivery and provides permissions for
# Cartographer to create templated objects
#
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: #@ data.values.service_account_name
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: delivery-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: delivery-role
subjects:
  - kind: ServiceAccount
    name: #@ data.values.service_account_name
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: delivery-role
rules:
  - apiGroups:
      - source.toolkit.fluxcd.io
      - kpack.io
      - kapp.k14s.io/v1alpha1
      - kappctrl.k14s.io
      - serving.knative.dev
      - carto.run
      - katapult.org
    resources:
      - gitrepositories
      - images
      - configs
      - apps
      - services
      - runnables
      - smoketests
    verbs:
      - list
      - create
      - update
      - delete
      - patch
      - watch
      - get
## kapp-controler deployment
  - apiGroups:
      - ""
      - networking.k8s.io
      - apps
      - extensions
      - batch
    resources:
      - configmaps
      - ingresses
      - services
      - deployments
      - secrets
      - replicasets
      - pods
      - jobs
    verbs:
      - list
      - create
      - update
      - delete
      - patch
      - watch
      - get
