apiVersion: carto.run/v1alpha1
kind: ClusterDelivery
metadata:
  name: simple-delivery
spec:
  selector:
    app.tanzu.vmware.com/workload-type: simple-delivery

  params:
    - name: application
      default: micropets
    - name: environment
      default: aws/prod-1  
  #
  #
  #   gitops-provider <--[gitops]---------   Service deployer
  #     GitRepository                           App
  #                                        |
  #   deployment-provider   <--[rules]-----| 
  #     GitRepository               
  #
  resources:     
    - name: gitops-provider-app
      templateRef:
        kind: ClusterSourceTemplate
        name: gitops-source-app
    - name: gitops-provider-env
      templateRef:
        kind: ClusterSourceTemplate
        name: gitops-source-env
    - name: deployment-rules-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: deployment-source        
    - name: deployment-provider  
      templateRef:
        kind: ClusterDeploymentTemplate
        name: micropet-app-deploy      
      deployment:
        resource: gitops-provider-app
      sources:
        - resource: gitops-provider-app
          name: gitops-app
        - resource: gitops-provider-env
          name: gitops-env
        - resource: deployment-rules-provider
          name: rules
      params:
        - name: deployment_rules
          default: kapp/none 

