apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:  
  name: smoke-micropets-smoke-test-template  
spec:
  template:
    apiVersion: katapult.org/v1alpha1   
    kind: SmokeTest
    metadata:
      name: $(deliverable.metadata.name)$-smoke-test
    spec: 
      url: http://front.mytanzu.xyz/$(deliverable.metadata.name)$/v1/data
      expectedResponseText: Total
      retryIntervalSeconds: 5
      startDelaySeconds: 30
      showPageContent: true
      timeout: 1
      maxRetries: 10