---
#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Namespace
metadata:
  name: asodemo
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: aso-password
  namespace: asodemo
spec:
  length: 64
  secretTemplate:
    type: Opaque
    stringData:
      password: $(value)
---
apiVersion: resources.azure.com/v1alpha1api20200601
kind: ResourceGroup
metadata:
  name: #@ data.values.RG
  namespace: asodemo
spec:
  location: #@ data.values.LOCATION
---
apiVersion: dbforpostgresql.azure.com/v1alpha1api20210601
kind: FlexibleServer
metadata:
  name: #@ data.values.SERVER
  namespace: asodemo
spec:
  location: #@ data.values.LOCATION
  owner:
    name: #@ data.values.RG
  version: "13"
  sku:
    name: Standard_D4s_v3
    tier: GeneralPurpose
  administratorLogin: #@ data.values.USERNAME
  administratorLoginPassword:    
    name: aso-password
    key: password
  storage:
    storageSizeGB: 128
---
apiVersion: dbforpostgresql.azure.com/v1alpha1api20210601
kind: FlexibleServersDatabase
metadata:
  name: votedb
  namespace: asodemo
spec:
  owner:
    name: #@ data.values.SERVER
  charset: utf8
---
apiVersion: dbforpostgresql.azure.com/v1alpha1api20210601
kind: FlexibleServersFirewallRule
metadata:
  name: asodemo-allow-all
  namespace: asodemo
spec:
  owner:
    name: #@ data.values.SERVER
  # The following address range allows anybody to connect to this server.
  # This should only be used for demo purposes and not in production!
  # There are other ways to control server access which are not covered here, you can see more about it here:
  # https://docs.microsoft.com/azure/postgresql/flexible-server/concepts-security#network-security
  startIpAddress: 0.0.0.0
  endIpAddress: 255.255.255.255
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: asodemo
stringData:
  USERNAME: #@ data.values.USERNAME
  SERVER: #@ data.values.SERVER+"postgres.database.azure.com"
  DATABASE: "votedb"
  PORT: "5432"
