---
#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Namespace
metadata:  
  name: #@ data.values.namespace
---
apiVersion: resources.azure.com/v1beta20200601
kind: ResourceGroup
metadata:
  name: #@ data.values.resourcegroup
  namespace: #@ data.values.namespace
spec:
  location: #@ data.values.location
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: aso-psql-secret
  namespace: #@ data.values.namespace
spec:
  length: 64
  secretTemplate:
    type: Opaque
    stringData:
      password: $(value)
---
apiVersion: dbforpostgresql.azure.com/v1beta20210601
kind: FlexibleServersDatabase
metadata:
  name: aso-psql
  namespace: #@ data.values.namespace
spec:
  azureName: mydb
  owner:
    name: aso-psql-fs   
  charset: utf8
---
apiVersion: dbforpostgresql.azure.com/v1beta20210601
kind: FlexibleServersFirewallRule
metadata:
  name: aso-psql
  namespace: #@ data.values.namespace
spec:
  owner:
    name: aso-psql-fs   
  startIpAddress: 0.0.0.0 #! only allow traffic from azure. See https://docs.microsoft.com/en-us/azure/postgresql/single-server/concepts-firewall-rules#connecting-from-azure. Warning not for production use.
  endIpAddress: 0.0.0.0
---
apiVersion: dbforpostgresql.azure.com/v1beta20210601
kind: FlexibleServer
metadata:
  name: aso-psql-fs
  namespace: #@ data.values.namespace
spec:
  location: #@ data.values.location
  azureName: #@ data.values.server
  owner:
    name: #@ data.values.resourcegroup     
  version: "13" 
  sku:
    name: Standard_D4s_v3
    tier: GeneralPurpose
  administratorLogin: myAdmin
  administratorLoginPassword:
    name: aso-psql-secret
    key: password
  storage:
    storageSizeGB: 32


