apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: micropet-gui-service-supply-chain
spec:
  selector:
    app.tanzu.vmware.com/workload-type: micropet-gui-service
  #
  #
  #   source-provider <--[src]-- image-builder  <--[img]--- config <--[config]--- deployer
  #     GitRepository               Image                     App                   App
  #
  #
  resources:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: micropet-source
    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: micropet-gui-image
      sources:
        - resource: source-provider
          name: source
    - name: configuration
      templateRef:
        kind: ClusterConfigTemplate
        name: micropet-gui-service-config
      sources:
        - resource: source-provider
          name: source
      images:
        - resource: image-builder
          name: image      
      params:        
        - name: brokerService
          value: $(workload.spec.params[?(@.name=="broker_service")].value)$        
        - name: observability
          value: $(workload.spec.params[?(@.name=="observability")].value)$
    - name: deploy
      templateRef:
        kind: ClusterTemplate
        name: micropet-gui-deploy      
      configs:
        - resource: configuration
          name: petconfig